# 选择 Python 3.10 基础镜像
FROM python:3.10-slim

# 设置工作目录
WORKDIR /app

# 安装必要的系统依赖
RUN apt-get update && apt-get install -y \
    ffmpeg build-essential gcc zlib1g-dev\
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 复制并安装 Python 依赖
COPY requirements_arm64.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements_arm64.txt 


# 复制全部源码到容器中
COPY . .


# 定义启动脚本
CMD ["/bin/bash", "/app/start.sh"]